### ISSUE TITLE
New time arguments

### ISSUE THREAD

**Issue by Vasileios-Mavroeidis** [oasis-tcs/openc2-apsc-stateless-packet-filter#109]
A suggestion for more refined time args regarding the SLPF that we may consider in the future.

Currently, we support start_time, stop_time, and duration

even though they make sense to have, a different categorization would be more useful, especially for packet filtering.

Parent classes:
-absolute or absolute_time
-periodic or periodic_time

Absolute_time can include start_time, stop_time, duration
Periodic, it is what it sounds, and it can support the following:
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday
daily
weekdays
weekend
start_time (without defined date)
stop_time (without defined date)
or duration (instead of using stop time)

**Comment by jmbrule** [comment]
This is actually an interesting topic, but I suspect it is more of a language spec thing than an SLPF specific.  I base that on the fact that the language spec already spells out temporal arguments, and this is an extension of that.  
May we close this issue here and resume it at the lang spec level?

**Comment by sparrell** [comment]
I agree it is LS, but don’t close until you can reference a LS issue with a link.

iPhone, iTypo, iApologize
________________________________

**Comment by jmbrule** [comment]
This is a language spec issue number 347 located at https://github.com/oasis-tcs/openc2-oc2ls/issues/347 

Closed from an SLPF point of view
