### ISSUE TITLE
Ballot Comment WD03 - Conformance Pofiles/Options

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#18]
I believe the conformance profiles listed (basic producer,  basic consumer, complete producer, complete producer) are over simplistic. The issue that created this need is options in the SLPF. As currently written, implementing the options is ‘all or none’. This will lead to either added complexity in implementations (eg adding the ‘update file’ command when it makes no sense) or partial compliance being the norm. Although it make the document longer, I think there need to be more conformance clauses of the type ‘If the blah-blah option is supported then a coformant implementation must whatever’ and that these clauses be independent of one another (eg so a conformant openc2 consumer with the ip-connection option not be required to have the update file command if it doesn't need one).
I will still vote yes but I believe the specification would be better with these changes.

**Comment by jmbrule** [comment]
The basic conformance level was defined so that every entity (be it hardware, cloud based or whatever) would have a known level of functionality.  
Within the SLPF, there were commands and arguments that were optional to implement.  These were within the scope (and validated with use cases) of the SLPF, but not required to implement for each and every SLPF.  The 'complete' conformance level was defined for products that implement (i.e. can accommodate) the optional features of the specification.  
The concern that 'partially compliant being the norm' is not warranted.  There may be devices that meet the 'basic' compliance and some subset of the options.  These ARE 'basic' conformant, not 'partial compliant'.  This is not overly burdensome for system owners. The language specification requires a 'query openc2' command that permits the orchestrator to determine the actuator's capabilities (beyond basic). 
As written, the spec has two conformance levels (basic and complete).  To define conformance levels to accommodate all of the possible combinations of required and optional commands and arguments would result in the number of conformance targets growing with the factorial of the number of options.

**Comment by jmbrule** [comment]
I will leave this topic open and request the AP SC to weigh in. Will determine the consensus prior to closing.

**Comment by jmbrule** [comment]
per the face to face we will make more conformance profiles

**Comment by jmbrule** [comment]
I believe that this issue is resolved.  We created additional conformance clauses and got rid of the 'complete' vs 'basic' terms. 
Please advise if you believe it should remain open, otherwise will close it at 16:00 on Feb 25
