### ISSUE TITLE
Simplify the targetspace for Deny and Allow

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#65]
Propose removing the ip_addr in the SLPF

**Comment by jmbrule** [comment]
We can achieve the same functionality and grossly simplify the specification if we adopt the following:  
Regardless of what the language spec cooks up, we can get by with the ipv4_connection and ipv6_connection targets. 
Based on a conversation with alex.everett@unc.edu, the ip_connection object is really a superset of the ip_addr target, therefore the orchestrator can issue the deny (or allow) using the ip_connection.  The hardware can execute the command and if there is extraneous information (such as port numbers or other parts of the five-tuple)  then write in the spec the appropriate handling.  
The presence of a mask does not preclude a single ip address.  According to one of our colleagues, you could put in a /32 mask or modern hardware will default to a single address if the mask is not present.  
Thoughts?

**Comment by jmbrule** [comment]
BTW, this proposed change makes the following issues moot:  SLPF-6; SLPF-15; SLPF-23;  and influences SLPF-24, SLPF-25;

**Comment by Vasileios-Mavroeidis** [comment]
> We can achieve the same functionality and grossly simplify the specification if we adopt the following:
> Regardless of what the language spec cooks up, we can get by with the ipv4_connection and ipv6_connection targets.
> Based on a conversation with [alex.everett@unc.edu](mailto:alex.everett@unc.edu), the ip_connection object is really a superset of the ip_addr target, therefore the orchestrator can issue the deny (or allow) using the ip_connection. The hardware can execute the command and if there is extraneous information (such as port numbers or other parts of the five-tuple) then write in the spec the appropriate handling.
> The presence of a mask does not preclude a single ip address. According to one of our colleagues, you could put in a /32 mask or modern hardware will default to a single address if the mask is not present.
> Thoughts?

Your colleague is absolutely right, BUT I would include a prefix in any case. In my mind that mitigates also the possibility of forgetting adding prefixes in general (it happens). So, when processing an OpenC2 allow/deny slpf command, my validation code would have to parse the prefix to do the appropriate mapping (and calculate the range of addresses) to the technology used (consumer). I may miss something here but the ip_addr target is prone to configuration mistakes since we don't specify if It is src or dst. We could though determine that in our validation code by checking if it is private or a public ip (more code and more code).

**Comment by jmbrule** [comment]
OK, I need to ask a question of @Vasileios-Mavroeidis , Alex and Kamervishi:  In the context of the SLPF, do we need to make a distinction between v4 and v6 in the ip_connection target?  Could we simply have the ip_connection target and let the orchestrator and firewall figure it out in context if it is a v4 or v6 address?

**Comment by jmbrule** [comment]
Also, request some guidance for chapter 2.3.  
If a firewall that only blocks or allows based on an ip address receives a: 
{
 "action": "deny",
  "target": {
    "ip_connection": {
      "protocol": "tcp",
      "src_addr": "1.2.3.4",
      "src_port": 10996,
      "dst_addr": "1.2.3.5",
      "dst_port": 80
    }

Then should it block based on the ip address and send a 501 target not supported? 
{"status": 501}  

Or as crazy as it sounds, should we define other error codes so we could send 
{"status":50X} 
When the orchestrator receives that error, it knows that the deny was issued based on the ip address but the firewall couldn't do anything based on the port number.

**Comment by Vasileios-Mavroeidis** [comment]
This is problematic now. The last draft of SLPF that I have read is v1.0-csprd0. I haven’t seen any way to distinct between IPV4 and IPV6 in the specification but I’m pretty sure that I have read something in the emails of OpenC2.

Simple logic says that introducing separate ipv4 and ipv6 src and dst targets in the ip_connection would make everything easier. That would allows us to include them in the schema that specifies the capabilities of an actuator. If we take for granted that all existing firewalls can make use of IPV6 ( which I guess is true) then validation code (regular expressions) can check the validity of the address and whether it is IPV4 or IPV6. Then the proxy does the appropriate mapping (e.g. OpenC2 to Cisco IOS commands).

-Vasileios

On 28 Jan 2019, at 19:00, Joe Brule <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I need to ask a question of @Vasileios-Mavroeidis<https://github.com/Vasileios-Mavroeidis> , Alex and Kamervishi: In the context of the SLPF, do we need to make a distinction between v4 and v6 in the ip_connection target? Could we simply have the ip_connection target and let the orchestrator and firewall figure it out in context if it is a v4 or v6 address?

**Comment by jmbrule** [comment]
Agree with @Vasileios-Mavroeidis  with a super minor caveat:  I would state that the ip_connection target has ipv4 and ipv6 properties vice 'targets'.  Not 100% on board with the notion of having nested targets.  Otherwise '+1'

**Comment by Vasileios-Mavroeidis** [comment]
It's a cost benefit analysis

Either we introduce ipv4 and ipv6 in the specification (an addition) or we deal with the possibility of getting an error from the actuator. The second would introduce overhead in the operations (time). On the other hand I believe that every technology processes ipv6 so maybe we can just skip the distinction in the specification.

Though other technologies may be affected. So if ipv4 and ipv6 is introduced in the "general " LS  we can also use it in the slpf.

Again another thought is in terms of coding. By specifying the version of ip most probably we don't need to create a function to find it's type but only to validate it.

Sorry if i introduce confusion or missing something.


On Jan 29, 2019 5:44 PM, Joe Brule <notifications@github.com> wrote:

Agree with @Vasileios-Mavroeidis<https://github.com/Vasileios-Mavroeidis> with a super minor caveat: I would state that the ip_connection target has ipv4 and ipv6 properties vice 'targets'. Not 100% on board with the notion of having nested targets. Otherwise '+1'

-

**Comment by jmbrule** [comment]
At this time, I do not see a particularly elegant way to accept the suggested way forward on this issue.  
There is a class of stateless packet filters that consume a 'five-tuple' which we accommodate with the ip_connection target.  (I will call 5-tuple)
There is another class of stateless packet filters that consume an ip address and will block (or allow) traffic based on the ip address REGARDLESS of whether or not it is the source or destination address. (I will call addr-only)
Here is the issue:  Elements within a five tuple are logical ANDs so to make the addr-only filters work, we would have to adopt one of the following solutions: 
* Issue two commands, one with the src address set and the other with the dst address set.  
* Define an argument that indicates that the elements of the fivetuple are logical 'OR' 
* Define a property within the ip_connection that is src_or_dst_ip_address

In my opinion, these are all 'klugy' and it would be a lot more elegant and straight forward to simply go back to the situation where we have an 'ip_addr' target and in the SLPF specification we state that if that is received, then the ip address is denied (or allowed) on the basis of the ip_address regardless of whether it was the source or destination 

Would appreciate a '+1' or a 'you are full of baloney' on this

**Comment by jmbrule** [comment]
Suggest closing this issue:  Please advise if you believe it needs to remain open, otherwise will close on Feb 19 at 15:00 eastern
